# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is {current_year}.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst

step_id_task:
  description: >
    You are given an input text which contains instructions. These instrucitons need to be converted into a comic. You are responsible for breaking down the input text into a list of steps. Each step that you extract must follow some standard. 
    Use the following criteria for steps splitting: (1)-Action Boundaries (Each distinct physical action or operation should be a separate step, When the primary object being manipulated changes, When a new tool or ingredient is introduced, When there's a shift in location or workspace) and (2)-State Changes (Points where the object/material undergoes a significant transformation, When a sub-component is completed, Natural pause points where verification/checking is needed)

    You must extract parts of text from the input and generate a list of steps based on the pydantic schema specified:

    - List of Steps. 
    Where each step has:
    - Step Number
    - Step Text

    <input_text>    
      {input_text}
    </input_text>
  expected_output: >
    The output must follow the pydantic schema strictly. There will be penalty if not followed.
  agent: agent_one

  illustration:
  description: > 
    You are given an input text which contains instructions. These instrucitons need to be converted into a comic. The input is already broken down into steps.

    Below is a description of a specific step from a series of instructions.
    
    Generate a prompt  which can be used by a text to image model to generate an image for the step. Send the prompt to the 
    tool provided to generated the image that depicts objects and backgrounds appropriately as per the requirements of the steps. 
    And the illustration should be in cartoon style. The prompts should be in less than 40 words.

    <step_text>
      {step_text}
    </step_text>
  expected_output: >   
    The output must follow the pydantic schema strictly. There will be penalty if not followed.       
  agent: agent_three
