# Task

illustration:
  description: >

    You are given a short story for kids on learning important lessons on life. The story will to be converted to 
    a picture book for fun reading and engagement for the kids. The story is already broken down into distinct scenes.

    Below is a description of a specific scence from a story. And a short summary of the story is also given below. 

    Generate a prompt which can be used by a text to image model to generate an image for the scene. Send the prompt to the 
    tool provided to generated the image that depicts characters and backgrounds appropriately as per the requirements of the scenes. 
    And the characters should be in cartoon style. The prompts should be in less than 40 words.

    <story_summary>
      {story_summary}
    <story_summary>

    <scene_description>
      {scene_description}
    </scene_description>
  expected_output: >
    The output must follow the pydantic schema strictly. There will be penalty if not followed.
  agent: visualartist
